name: AZenith

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build.yml"
      - ".github/scripts/**"
      - "mainfiles/**"
      - "preloadbin/**"
      - "cargo/**"
      - "webui/**"
      - "gamelist.txt"
      - "version"

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    name: Build Flashable ZIP + Rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Add ARCH Target
        run: |
          rustup target add aarch64-linux-android armv7-linux-androideabi

      - name: Install cargo-ndk
        run: cargo install cargo-ndk

      - name: Build Rust Daemon
        run: |
          cd ./cargo
          cargo ndk --target aarch64-linux-android build --release
          cargo ndk --target armv7-linux-androideabi build --release

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.2

      - name: Build WebRoots
        working-directory: ./webui
        run: |
          bun install
          bun run build
          cp -r ./dist/* ../mainfiles/webroot

      - name: Compile Flashable ZIP
        run: bash .github/scripts/compile_zip.sh

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: AZenith-build
          path: mainfiles/**/*.zip