name: AZenith

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build.yml"
      - ".github/scripts/**"
      - "mainfiles/**"
      - "preloadbin/**"
      - "Cargo/**"
      - "webui/**"
      - "gamelist.txt"
      - "version"

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    name: Build Flashable ZIP + Rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rust-src,cargo

      - name: Add Android targets
        run: |
          rustup target add aarch64-linux-android armv7-linux-androideabi

      - name: Build Rust Daemon
        run: |
          cargo build --release --target aarch64-linux-android
          cargo build --release --target armv7-linux-androideabi

      - name: Build WebRoots
        working-directory: ./webui
        run: |
          bun install
          bun run build
          cp -r ./dist/* ../mainfiles/webroot

      - name: Compile Flashable ZIP
        run: bash .github/scripts/compile_zip.sh

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: AZenith-build
          path: mainfiles/**/*.zip